// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD7pADOF-Qp9FBQDIqB-JYriuz-0GJX8k',
    appId: '1:359330817625:web:ed48145befc859355a7348',
    messagingSenderId: '359330817625',
    projectId: 'blog-4bed1',
    authDomain: 'blog-4bed1.firebaseapp.com',
    storageBucket: 'blog-4bed1.appspot.com',
    measurementId: 'G-KW4485BDHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6qpX7KZcdQMDweenW49gr4uWwdHBChDw',
    appId: '1:359330817625:android:3f94fe8246908dcd5a7348',
    messagingSenderId: '359330817625',
    projectId: 'blog-4bed1',
    storageBucket: 'blog-4bed1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7oVrYNy2fKwqe5z1_V-bsH9LIuBwCc7E',
    appId: '1:359330817625:ios:75601a82e5bc5ee45a7348',
    messagingSenderId: '359330817625',
    projectId: 'blog-4bed1',
    storageBucket: 'blog-4bed1.appspot.com',
    iosClientId: '359330817625-40iu6vh58030ubah7c0qaq41jqnebt7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.blog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7oVrYNy2fKwqe5z1_V-bsH9LIuBwCc7E',
    appId: '1:359330817625:ios:75601a82e5bc5ee45a7348',
    messagingSenderId: '359330817625',
    projectId: 'blog-4bed1',
    storageBucket: 'blog-4bed1.appspot.com',
    iosClientId: '359330817625-40iu6vh58030ubah7c0qaq41jqnebt7d.apps.googleusercontent.com',
    iosBundleId: 'com.example.blog',
  );
}
